2024-02-14 23:07:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d717079520375141452e5361","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:07:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:07:21 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:07:21 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:08:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079521192461383e7b7b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:08:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:08:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:08:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079521204761474e7b7b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:08:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:08:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:08:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079521227081613e7b7b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:08:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:08:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:08:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079521259611877e7b7b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:08:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:08:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:08:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:14:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17079524638941027e4de3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:14:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:14:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:14:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17079524651581081e4de3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:14:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:14:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:14:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17079524674051302e4de3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:14:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:14:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:14:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fc17079524706521537e4de3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:14:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:14:34 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:14:34 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:17:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526330312942e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:17:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526342743029e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:17:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526365223206e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:17:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526397723405e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:23 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:17:23 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:17:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526601014880e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:17:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526613434952e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:17:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526635915175e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:17:47 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d517079526668395524e7b7a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:17:47 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:17:51 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:17:51 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:21:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800817079528906965012e6175","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:21:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:21:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:21:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800817079528919495059e6175","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:21:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:21:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:21:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800817079528941915180e6175","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:21:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:21:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:21:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800817079528974265372e6175","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:21:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:21:41 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:21:41 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:29:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d317079533632837680e6e04","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:29:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:29:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:29:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d317079533645177819e6e04","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:29:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:29:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:29:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d317079533667718143e6e04","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:29:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:29:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:29:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070d317079533700138399e6e04","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:29:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:29:34 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:29:34 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:30:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f917079534156343938e7ef9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:30:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:30:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:30:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f917079534168803971e7ef9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:30:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:30:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:30:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f917079534191434120e7ef9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:30:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:30:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:30:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f917079534223864318e7ef9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:30:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:30:26 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:30:26 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:31:55 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800f17079535156916257e3550","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:31:55 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:31:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:31:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800f17079535169296348e3550","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:31:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:31:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:31:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800f17079535191566506e3550","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:31:59 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:32:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:32:02 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800f17079535223906821e3550","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:32:02 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:32:06 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:32:06 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:33:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536254832764efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:33:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:33:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:33:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536267312850efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:33:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:33:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:33:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536289753014efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:33:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:33:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:33:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536322253203efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:33:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:33:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:33:56 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:34:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536747296161efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:34:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:34:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:34:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536759736259efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:34:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:34:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:34:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536782186399efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:34:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:34:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:34:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800617079536814676596efa36","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:34:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:34:45 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:34:45 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:35:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f017079537293306344e5dbb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:35:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:35:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:35:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f017079537305636395e5dbb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:35:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:35:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:35:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f017079537328046507e5dbb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:35:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:35:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:35:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0070f017079537360396661e5dbb","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:35:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:35:40 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:35:40 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:46:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/25/12/45/44/115464732_p0.png
2024-02-14 23:50:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-14 23:50:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:56:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb17079549841478994e56d8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:56:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:56:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:56:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb17079549853831057e56d8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:56:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:56:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:56:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb17079549876431232e56d8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:56:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:56:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:56:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb17079549908871483e56d8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:56:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:56:35 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:56:35 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-14 23:59:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800a17079551698746065e731b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:59:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:59:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-14 23:59:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800a17079551711076127e731b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:59:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:59:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-14 23:59:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800a17079551733446298e731b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:59:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:59:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-14 23:59:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800a17079551765826568e731b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-02-14 23:59:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-02-14 23:59:40 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-14 23:59:40 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/17134901/Ringeko | 凛子 - 17134901.
2024-02-15 00:01:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/27/09/36/46/112882586_p0.png
2024-02-15 00:13:06 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-15 00:15:10 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-02-15 10:16:28 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-15 10:18:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:18:15 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:18:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:18:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:18:34 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:18:35 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:18:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:18:51 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:18:52 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:27:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:27:26 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:27:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:27:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:27:57 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:27:58 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:33:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:33:25 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:33:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:35:58 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:35:58 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:35:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:40:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:40:06 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:40:07 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:41:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:41:26 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:41:27 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:42:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/10/02/49/23/110688256_p0.jpg
2024-02-15 10:43:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:43:14 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:43:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:43:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 10:43:37 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 10:43:38 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 10:44:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 10:44:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:45:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 10:45:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:53:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:53:49 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:53:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 10:56:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 10:56:45 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 10:56:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:00:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:00:52 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:00:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:01:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-wdkgp</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/02/15 19:01:14</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-02-15 11:01:14 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 11:01:15 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 11:01:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-wdkgp</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/02/15 19:01:15</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-02-15 11:01:15 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 11:01:17 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2024-02-15 11:01:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-wdkgp</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/02/15 19:01:18</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-02-15 11:01:18 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 11:01:21 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2024-02-15 11:03:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:03:26 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:03:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:07:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:07:12 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:07:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:14:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:14:37 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:14:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:17:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:17:45 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:17:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:18:24 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/25/00/00/25/114518241_p0.jpg
2024-02-15 11:25:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:25:11 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:25:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:26:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:26:20 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:26:21 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:28:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:28:40 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:28:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:31:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 11:31:44 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 11:31:45 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 11:34:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/15/15/39/34/116082801_p0.png
2024-02-15 11:41:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:41:10 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:41:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:42:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/13/19/10/56/113380826_p0.png
2024-02-15 11:50:03 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-02-15 11:50:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 11:50:22 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 11:50:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 11:59:45 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/04/19/45/23/113951463_p0.png
2024-02-15 12:02:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:02:33 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:02:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 12:05:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:05:14 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:05:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 12:15:31 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-15 12:17:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-hxvs2</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/02/15 20:17:16</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-02-15 12:17:16 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:17:17 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 12:17:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>security-pgw-90b2f6b7d69951d209f28a873243d040-hxvs2</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/02/15 20:17:17</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-02-15 12:17:17 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:17:19 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2024-02-15 12:19:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 12:19:29 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:19:30 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 12:22:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/07/13/16/54/114960296_p0.png
2024-02-15 12:26:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:26:46 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:26:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 12:27:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 12:27:27 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:27:28 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 12:27:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 12:27:31 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:27:33 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2024-02-15 12:29:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:29:15 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:29:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 12:35:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:504:Gateway Timeout
2024-02-15 12:35:20 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-02-15 12:35:21 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-15 12:36:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:36:38 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:36:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 12:40:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-15 12:40:46 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-15 12:40:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 22:13:46 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-15 22:34:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/02/20/00/09/114815592_p0.jpg
2024-02-15 22:50:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/06/22/43/42/114943532_p0.jpg
2024-02-15 23:02:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/04/05/00/24/22/97412983_p0.png
2024-02-15 23:12:08 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-02-15 23:33:51 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:33:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 23:34:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:34:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-15 23:34:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3eba287c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2024-02-15 23:35:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:35:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-15 23:35:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3ebaaac70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2024-02-15 23:36:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3ebaaa430>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /adrive/v2/file/createWithFolders
2024-02-15 23:37:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:37:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 23:38:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:38:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-15 23:38:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:39:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-02-15 23:39:33 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:39:37 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-02-15 23:39:37 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/69328034/netural - 69328034.
2024-02-15 23:40:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:40:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-15 23:40:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-15 23:40:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-16 00:12:46 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-16 10:16:27 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-16 10:37:24 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-16 10:37:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-16 10:42:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-16 10:42:50 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-16 10:42:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-16 10:43:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/12/00/00/28/115088749_p0.png
2024-02-16 12:08:55 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/11/08/00/03/115946156_p0.jpg
2024-02-16 12:15:30 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-16 12:46:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/19/00/00/31/114345300_p0.jpg
2024-02-16 12:50:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/26/00/00/51/115480562_p0.png
2024-02-16 12:57:52 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-02-16 22:14:01 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-16 22:39:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/12/00/00/28/115088749_p0.png
2024-02-16 22:46:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/05/21/00/15/54/108298637_p0.jpg
2024-02-16 22:59:37 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/109140616/109140616_ugoira0.gif, upload original page.
2024-02-16 23:13:17 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/27/21/32/25/113763133_p0.png
2024-02-17 00:08:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/19/20/00/05/115301459_p0.png
2024-02-17 00:13:02 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-17 10:14:36 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-17 10:18:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/21/12/18/22/115352027_p0.jpg
2024-02-17 11:12:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/22/00/01/04/103791526_p0.jpg
2024-02-17 11:51:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/15/12/00/01/115187915_p0.jpg
2024-02-17 11:53:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/08/12/21/06/46/110768338_p0.jpg
2024-02-17 12:13:36 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-17 12:20:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/04/20/11/24/115763682_p0.jpg
2024-02-17 22:15:20 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-17 22:18:22 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-17 22:18:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-17 22:20:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-17 22:20:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-17 22:24:55 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/09/01/02/41/109747127_p0.jpg
2024-02-18 10:15:46 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-18 10:26:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/18/00/00/21/116153827_p0.jpg
2024-02-18 10:31:55 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/10/21/19/51/24/102115061_p0.jpg
2024-02-18 11:11:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/12/25/08/00/01/103889726_p0.jpg
2024-02-18 11:46:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/23/08/48/34/114456546_p0.png
2024-02-18 11:53:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:504:Gateway Timeout
2024-02-18 11:53:44 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:JsonValueError.
2024-02-18 11:53:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-18 12:14:47 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-02-18 12:15:01 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/24/00/00/49/113655137_p0.jpg
2024-02-18 12:38:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:38:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-18 12:40:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:40:03 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-18 12:41:15 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:41:16 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-02-18 12:42:25 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:42:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-18 12:43:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:43:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-02-18 12:43:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:43:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-02-18 12:45:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-02-18 12:45:27 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
